version: "3.7"
services:
  web:
    build:
      context: .
      target: release
    image: quid-dock.jfrog.io/quid/spinnaker-demo/web

  test:
    build:
      context: .
      target: builder
    command: go test -v